version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/Relic-poc-test-app-rails-cd-v1
hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 3600
      # runas: root
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 3600
      # runas: root
  ApplicationStart:
    - location: scripts/application_start.sh
      timeout: 3600
      # runas: root