workflows:
  version: 2
  build-test-and-approval-deploy:
    jobs:
      - build:
        docker:
          - image: cimg/php:7.1 # The primary container where steps are run
          - image: cimg/mysql:8.0
            environment:
              MYSQL_ROOT_PASSWORD: rootpw
              MYSQL_DATABASE: test_db
              MYSQL_USER: user
              MYSQL_PASSWORD: passw0rd
      - test1: # your custom job; runs test suite 1
          requires: # test1 will not run until the `build` job is completed.
            - build
      - test2: # another custom job; runs test suite 2,
          requires: # test2 is dependent on the success of job `test1`
            - test1
      - hold: # <<< A job that will require manual approval in the CircleCI web application.
          type: approval # <<< This key-value pair will set your workflow to a status of "On Hold"
          requires: # We only run the "hold" job when test2 has succeeded
           - test2
      # On approval of the `hold` job, any successive job that requires the `hold` job will run.
      # In this case, a user is manually triggering the deploy job.
      - deploy:
          requires:
            - hold
