jobs:
  build:
    docker:
      - image: circleci/ruby:2.5.7-node-browsers
        environment:
          RAILS_ENV: test
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        environment:
          RAILS_ENV: test
          TZ: /usr/share/zoneinfo/Asia/Tokyo
          MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
          MYSQL_ROOT_HOST: "%"
      - image: redis
    working_directory: ~/Relic-poc-test-app-rails-cd-v1
    steps:
      - checkout
      - restore_cache:
          keys:
            - v5-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v5-dependencies-
      - run:
          name: Check version ruby
          command: |
            ruby --version
      - run:
          name: Install Latest Chrome
          command: |
            sudo apt install libappindicator3-1 libgbm1
            curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome.deb
            sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
            rm google-chrome.deb
      - run:
          name: Install dependencies
          command: |
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - run:
          name: Install dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - ./vendor/bundle
            - ./node_modules
          key: v5-dependencies-{{ checksum "Gemfile.lock" }}-{{ checksum "yarn.lock" }}
      - run:
          name: Database setup
          command: |
            rm -rf config/database.yml
            mv config/database.ci.yml config/database.yml
      - run:
          name: Database migrate
          command: |
            bundle exec rake db:create
            bundle exec rake db:schema:load
            bundle exec bin/webpack
      # - run:
      #     name: Rails webpack
      #     command: |
      #       bundle exec bin/webpack
  test:
  deploy:
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          # filters:
          #   branches:
          #     only:
          #       - main
