default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: 127.0.0.1
  username: root
  password:

development:
  <<: *default
  database: relic-poc-development

test:
  <<: *default
  database: relic-poc-test

production:
  <<: *default
  database: relic-poc-production
