default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] || ENV['MYSQL_ROOT_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || 'localhost' %>

development:
  <<: *default
  database: circle_test

test:
  <<: *default
  database: circle_test
